sudo: required

services: docker

before_install:
  - docker-compose up --build

scrip:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test  